### ISSUE TITLE
Support for Statamic 5 and Laravel 11

### ISSUE THREAD

**Issue by doriengr** [statamic-rad-pack/meilisearch#37]
### Description

I think the title is self-explanatory. In any case, it would be great if the addon is updated soon.

### Steps to reproduce

See above

### Environment

See above

**Comment by ryanmitchell** [comment]
v3.3.0+ supports both - its just been released.

**Comment by duncanmcclean** [comment]
Statamic 5 compatibility added in [v3.3.0](https://github.com/statamic-rad-pack/meilisearch/releases/tag/v3.3.0).
