### ISSUE TITLE
Limit doesn't seem to be applied

### ISSUE THREAD

**Issue by electroflame** [statamic-rad-pack/meilisearch#9]
**Describe the bug**
When using the {{ search:results }} tag, using {{ search:results limit=10 }} doesn't seem to properly limit the results.

**Versions**
- elvenstar/statamic-meilisearch package version: 1.1.0

**Expected behavior**
When using the limit modifier, the returned results should be limited to the specified number.

**Additional context**
This seems like a bug, but it's complicated by how Meilisearch handles limits, I think.

For the limit to actually apply to what Meilisearch returns, it needs to be passed in via the searchUsingApi method.
`public function searchUsingApi($query, $filters = [], $options = [])`

Specifically, as a filter according to this: [https://docs.meilisearch.com/reference/api/search.html#limit](https://docs.meilisearch.com/reference/api/search.html#limit).

By changing the Query's call from this:
`return $this->index->searchUsingApi($query);`
to this:
`return $this->index->searchUsingApi($query, ['limit' => 100]);`

I can see search results up to 100 being reported.  By default, Meilisearch will only return the first 20 results, unless its limit value is overridden.

This is actually kind of a big deal, as it's locking all search:results requests to 20 results, no matter what's actually being requested.

Looking at the Search Settings page, Meilisearch also seems to support Offset values in much the same way, so it might be worth supporting that as well?

As it stands right now, I'm not sure how to work around this, short of editing the actual Query.php file (which I'd like to avoid).  Is it possible to grab the data from the search tag and use it in the Index?

Thanks for your work on the addon so far, it's super handy (aside from this locked search result issue)!

**Comment by flolanger** [comment]
+1

Thank you for your work as well! The setup was pretty easy.

But I need to change the limit of the search results as well, because 20 just isn't enough. 😅
